apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ncq8qdu2s-java-quarkus
  janus-idp.io/tekton: ncq8qdu2s-java-quarkus
  backstage.io/kubernetes-id: ncq8qdu2s-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ncq8qdu2s-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
